export const theoryData = {

  "KS3": {
    "Computer Systems": {
      "Hardware Components": [
        {question:"What does CPU stand for?",correct:["Central Processing Unit","Central processing unit"],wrong:["Central Process Unit","Core Processing Unit","Computer Processing Unit","Control Processing Unit","Central Processor Unit","Core Processor Unit","Central Processing Utility","Computer Processor Unit","Central Program Unit","Core Process Unit","Central Processing Module","Central Processor Utility","Control Processor Unit","Core Processing Utility","Central Processing Engine","Central Process Utility"]},
        {question:"What is the main function of the CPU?",correct:["Process instructions and data","Executes instructions and processes data"],wrong:["Stores files permanently","Displays graphics only","Connects to the internet","Manages file storage","Provides power","Cools the system","Handles input devices only","Prints documents","Stores backup data","Controls network traffic","Runs the monitor","Handles sound output","Stores BIOS settings","Manages user accounts","Controls USB ports only","Stores operating system permanently"]},
        {question:"Which component is the 'brain' of the computer?",correct:["CPU","Central Processing Unit"],wrong:["RAM","Hard Drive","GPU","Motherboard","Power Supply","Cache","ROM","Cooling Fan","Network Card","SSD","BIOS","Heat Sink","Sound Card","Expansion Card","Optical Drive","Chipset"]},
        {question:"What does RAM stand for?",correct:["Random Access Memory","Random access memory"],wrong:["Rapid Access Memory","Read Access Memory","Random Active Memory","Real-time Access Memory","Random Allocation Memory","Remote Access Memory","Random Application Memory","Random Array Memory","Runtime Access Memory","Readable Access Memory","Random Access Module","Random Access Machine","Random Access Mechanism","Rapid Allocation Memory","Read Active Memory","Random Accessible Memory"]},
        {question:"What is RAM mainly used for?",correct:["Running currently active programs","Temporarily storing data in use"],wrong:["Permanent file storage","Cooling the CPU","Displaying graphics","Connecting to networks","Storing BIOS settings","Powering components","Storing backup data","Managing peripherals","Handling input only","Printing documents","Managing internet access","Controlling power usage","Storing firmware","Managing drivers","Running the PSU","Handling sound output"]},
        {question:"What type of memory is ROM?",correct:["Permanent memory","Non-volatile memory"],wrong:["Volatile memory","Temporary memory","Cache memory","Virtual memory","External memory","Secondary memory","Dynamic memory","Working memory","Backup memory","Expandable memory","Network memory","Removable memory","Optical memory","Shared memory","Active memory","Runtime memory"]},
        {question:"What does GPU stand for?",correct:["Graphics Processing Unit","Graphics processing unit"],wrong:["General Processing Unit","Graphical Processor Unit","Graphic Performance Unit","General Performance Unit","Graphics Program Unit","Game Processing Unit","Graph Processing Utility","Graphics Performance Utility","Game Performance Unit","Graphics Processor Utility","General Processor Utility","Graphic Processing Utility","Graphical Performance Unit","General Graphics Unit","Graphic Processing Unit","Graph Unit Processor"]},
        {question:"What is the main role of the GPU?",correct:["Process graphics and images","Renders visual output"],wrong:["Store data permanently","Manage system files","Run the operating system","Provide power","Cool the CPU","Handle network connections","Store BIOS settings","Manage RAM usage","Control peripherals","Run background processes","Store programs","Manage storage devices","Control power supply","Handle user input","Manage security settings","Handle printing"]},
        {question:"What does HDD stand for?",correct:["Hard Disk Drive","Hard disk drive"],wrong:["Hard Data Drive","Hardware Disk Drive","High Data Drive","Hard Drive Disk","High Disk Drive","Hard Digital Drive","Hardware Data Drive","High Digital Drive","Hard Disk Device","Hardware Disk Device","High Disk Device","Hard Data Device","Hardware Data Device","High Drive Disk","Hard Device Drive","Hardware Drive Disk"]},
        {question:"What is an SSD?",correct:["Solid State Drive","Solid state drive"],wrong:["Static Storage Device","Secure Storage Disk","Solid Storage Disk","System Storage Drive","Secondary State Drive","Solid System Device","Static State Disk","Secure State Drive","Solid Storage Device","System State Disk","Secondary Storage Disk","Solid System Disk","Secure Storage Device","Static Storage Disk","System Storage Disk","Solid State Disk"]},
        {question:"Which component connects all hardware parts together?",correct:["Motherboard","The motherboard"],wrong:["CPU","RAM","Hard Drive","GPU","Power Supply","Cooling Fan","Network Card","BIOS","Cache","SSD","ROM","Heat Sink","Sound Card","Expansion Card","Optical Drive","Chipset"]},
        {question:"What does PSU stand for?",correct:["Power Supply Unit","Power supply unit"],wrong:["Processing Supply Unit","Power System Unit","Primary Supply Unit","Power Storage Unit","Processing System Unit","Power Support Unit","Primary System Unit","Processing Storage Unit","Power Source Utility","Power System Utility","Primary Supply Utility","Power Service Unit","Processing Source Unit","Power Setup Unit","Primary Source Unit","Power Supply Utility"]},
        {question:"What is the function of the PSU?",correct:["Provide power to components","Supplies electrical power to hardware"],wrong:["Store data","Process instructions","Display images","Run programs","Cool the system","Manage memory","Connect to internet","Store BIOS","Control peripherals","Run graphics","Manage files","Store operating system","Handle input","Manage storage","Control software updates","Manage users"]},
        {question:"What is cache memory used for?",correct:["Temporary storage of frequently used data","Stores frequently accessed instructions for quick access"],wrong:["Long-term storage","Power supply","Cooling","Network access","Display graphics","Store operating system","Backup storage","Manage peripherals","Run programs","Store BIOS","Handle input","Manage files","Store user data permanently","Control hardware","Manage internet","Store backups"]},
        {question:"Which is an input device?",correct:["Keyboard","Mouse"],wrong:["Monitor","Printer","Speakers","Projector","Headphones","Display screen","Plotter","GPU","Hard Drive","CPU","SSD","PSU","Motherboard","Heat sink","Fan","ROM"]},
        {question:"Which is an output device?",correct:["Monitor","Printer"],wrong:["Mouse","Keyboard","Scanner","Microphone","Webcam","Touchpad","Stylus","Game controller","Barcode scanner","Graphics tablet","Trackball","CPU","RAM","GPU","SSD","Motherboard"]},
        {question:"What does BIOS stand for?",correct:["Basic Input Output System","Basic input output system"],wrong:["Binary Input Output System","Basic Internal Output System","Binary Internal Operating System","Basic Input Operating System","Binary Input Operating System","Basic Internal Operating Software","Basic Input Output Software","Binary Internal Output Software","Basic Interface Output System","Binary Interface Operating System","Basic Internal Output Software","Binary Input Output Software","Basic Interface Operating Software","Binary Internal Output System","Basic Input System Output","Binary Output Input System"]},
        {question:"What is the role of the BIOS?",correct:["Starts up the computer and loads the OS","Initializes hardware during boot"],wrong:["Stores files","Processes graphics","Runs applications","Stores user data","Manages RAM","Provides power","Cools system","Handles input devices","Connects networks","Manages storage","Displays output","Runs games","Manages internet","Controls sound","Runs GPU","Stores backups"]},
        {question:"What is virtual memory?",correct:["Extra storage used as RAM","Uses disk space to extend memory"],wrong:["Physical RAM","Permanent memory","Cache memory","GPU memory","ROM storage","External memory only","Network storage","Backup storage","BIOS memory","CPU memory","Secondary cache","Optical memory","Flash memory","Cloud memory","System firmware","Internal storage only"]},
        {question:"What factor most affects CPU performance?",correct:["Clock speed","Number of cores"],wrong:["Screen size","Keyboard type","Mouse sensitivity","Case design","Monitor resolution","Speaker quality","Printer speed","Cable type","USB ports","Storage colour","Case fans only","Power button type","LED lighting","Case size","Desk setup","Internet speed"]}
      ],

      "Software (System vs Application)": [
        {question:"What is system software?",correct:["Controls the computer","Manages hardware"],wrong:["Creates documents","Plays music","Edits photos","Browses the web","Runs games","Sends emails","Makes presentations","Stores files","Draws pictures","Plays videos","Writes code","Prints documents","Opens websites","Records audio","Takes screenshots","Runs apps"]},
        {question:"Which of the following is system software?",correct:["Operating system","OS"],wrong:["Word","Chrome","PowerPoint","Photoshop","Spotify","Teams","Zoom","Paint","Calculator","Camera app","Notes app","Media Player","File editor","Web browser","Music app","Video editor"]},
        {question:"What is application software?",correct:["Helps users do tasks","User programs"],wrong:["Controls hardware","Manages memory","Starts the computer","Runs the BIOS","Updates drivers","Controls storage","Manages CPU","Runs background tasks","Loads the OS","Handles booting","Controls RAM","Manages power","Runs firmware","Controls devices","Manages system files","Runs system tools"]},
        {question:"Which of the following is application software?",correct:["Word","Chrome"],wrong:["Windows","macOS","Linux","BIOS","Drivers","Firmware","Task Manager","File Explorer","System Monitor","Disk Manager","Boot Loader","Control Panel","Device Manager","Terminal","Command Prompt","Registry Editor"]},
        {question:"What is the purpose of an operating system?",correct:["Runs the computer","Manages hardware"],wrong:["Creates documents","Edits videos","Plays games","Designs graphics","Stores files","Prints pages","Plays music","Browses websites","Sends messages","Takes photos","Records audio","Makes slideshows","Writes emails","Draws images","Runs apps only"]},
        {question:"Which of the following is NOT application software?",correct:["BIOS","Firmware"],wrong:["Word","Excel","Chrome","PowerPoint","Photoshop","Teams","Zoom","Spotify","Notepad","Paint","Calculator","Camera","Media Player","Email app","Web browser","Video editor"]},
        {question:"What is a device driver?",correct:["Controls hardware","Helps devices work"],wrong:["Edits images","Stores files","Plays videos","Manages passwords","Updates apps","Removes viruses","Controls internet","Runs games","Creates documents","Plays music","Browses websites","Prints pages","Sends emails","Draws pictures","Records audio"]},
        {question:"Which is an example of system software?",correct:["Driver","Operating system"],wrong:["Web browser","Video editor","Music player","Presentation app","Spreadsheet app","Game launcher","Chat app","Photo editor","Drawing app","Email app","Camera app","Media player","Notes app","Calendar app","Weather app","File editor"]},
        {question:"What is utility software?",correct:["Maintains the system","Performs system tasks"],wrong:["Plays games","Writes essays","Browses websites","Edits photos","Creates documents","Plays music","Runs apps","Designs graphics","Makes spreadsheets","Records audio","Prints pages","Sends emails","Draws pictures","Runs games","Edits videos","Stores files"]},
        {question:"Which of the following is utility software?",correct:["Antivirus","Disk cleanup"],wrong:["Word","Chrome","PowerPoint","Photoshop","Spotify","Teams","Zoom","Paint","Calculator","Camera","Media Player","Email app","Web browser","Video editor","Music app"]},
        {question:"What is the purpose of antivirus software?",correct:["Protects against malware","Finds and removes viruses"],wrong:["Creates documents","Edits photos","Plays music","Runs the OS","Manages hardware","Controls RAM","Prints pages","Stores files","Browses websites","Sends emails","Designs graphics","Runs games","Records audio","Makes spreadsheets","Edits videos"]},
        {question:"What is the purpose of file compression software?",correct:["Reduce file size","Make files smaller"],wrong:["Play music","Edit videos","Browse the web","Run the OS","Manage RAM","Print documents","Store files permanently","Scan images","Record audio","Design graphics","Run games","Send emails","Make spreadsheets","Edit photos","Install apps"]},
        {question:"What is firmware?",correct:["Software built into hardware","Controls basic hardware functions"],wrong:["Application software","Utility software","Web browser","Video editor","Music player","Game launcher","Spreadsheet app","Presentation app","Photo editor","Drawing app","Email app","Camera app","Media player","Notes app","Calendar app"]},
        {question:"What is the purpose of a driver?",correct:["Helps hardware communicate with OS","Allows devices to work"],wrong:["Plays music","Edits photos","Runs games","Browses websites","Stores files","Prints pages","Manages RAM","Controls CPU","Runs BIOS","Designs graphics","Makes spreadsheets","Edits videos","Records audio","Sends emails","Draws pictures"]},
        {question:"Which software manages files and folders?",correct:["Operating system","OS"],wrong:["Word","Chrome","Photoshop","Spotify","Teams","Zoom","Paint","Calculator","Camera","Media Player","Email app","Web browser","Video editor","Music app","Game launcher","Spreadsheet app"]},
        {question:"Which software loads first when a computer starts?",correct:["BIOS","Firmware"],wrong:["Windows","Chrome","Word","Photoshop","Spotify","Teams","Zoom","Paint","Calculator","Camera","Media Player","Email app","Web browser","Video editor","Music app","Game launcher"]},
        {question:"What is the purpose of system updates?",correct:["Fix bugs","Improve security"],wrong:["Play music","Edit photos","Browse websites","Run games","Create documents","Print pages","Store files","Record audio","Scan images","Design graphics","Make spreadsheets","Edit videos","Send emails","Draw pictures","Install apps"]},
        {question:"Which software helps keep your computer safe?",correct:["Antivirus","Firewall"],wrong:["Word","Chrome","Photoshop","Spotify","Teams","Zoom","Paint","Calculator","Camera","Media Player","Email app","Web browser","Video editor","Music app","Game launcher","Spreadsheet app"]},
        {question:"What is the purpose of a firewall?",correct:["Blocks unwanted network access","Protects the system"],wrong:["Plays music","Edits photos","Runs games","Browses websites","Stores files","Prints pages","Manages RAM","Controls CPU","Runs BIOS","Designs graphics","Makes spreadsheets","Edits videos","Records audio","Sends emails","Draw pictures"]},
        {question:"What is the purpose of system tools?",correct:["Maintain the computer","Manage system settings"],wrong:["Play music","Edit photos","Browse websites","Run games","Create documents","Print pages","Store files","Record audio","Scan images","Design graphics","Make spreadsheets","Edit videos","Send emails","Draw pictures","Install apps"]}
      ]
    },

    "Programming": {

      "Data Types": [

        {question:"Which data type is used to store text in Python?",correct:["String","str"],wrong:["Integer","Float","Boolean","Decimal","Char","List","Tuple","Dictionary","Binary","Byte","Object","DataBlock","NumberText","WholeNumber","TrueFalse","DigitString","DataType"]},
        {question:"Which data type stores whole numbers in Python?",correct:["Integer","int"],wrong:["Float","String","Boolean","Decimal","Char","List","Tuple","Dictionary","Binary","Byte","Object","DataBlock","NumberText","TrueFalse","DigitString","DataType","NumBlock"]},
        {question:"Which data type stores numbers with decimals?",correct:["Float","float"],wrong:["Integer","String","Boolean","DecimalInteger","Char","List","Tuple","Dictionary","Binary","Byte","Object","DataBlock","WholeNumber","TrueFalse","DigitString","DataType","NumBlock"]},
        {question:"Which data type stores True or False values?",correct:["Boolean","bool"],wrong:["String","Integer","Float","TrueString","FalseString","Binary","BitType","Char","List","Tuple","Dictionary","Byte","Object","DataType","NumBlock","WholeNumber","Decimal"]},
        {question:"Which data type would store a person's name?",correct:["String","str"],wrong:["Integer","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","Decimal","DigitString","NumBlock"]},
        {question:"Which data type would store someone's age?",correct:["Integer","int"],wrong:["Float","String","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","Decimal","DigitString","NumBlock","WholeNumber"]},
        {question:"Which data type would store a price like 4.99?",correct:["Float","float"],wrong:["Integer","String","Boolean","DecimalInteger","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","DigitString","NumBlock"]},
        {question:"Which data type would store whether a user is logged in (True/False)?",correct:["Boolean","bool"],wrong:["String","Integer","Float","TrueString","FalseString","Binary","BitType","Char","List","Tuple","Dictionary","Byte","Object","DataType","NumBlock","WholeNumber","Decimal"]},
        {question:"Which data type is 'Hello World'?",correct:["String","str"],wrong:["Integer","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","Decimal","DigitString","NumBlock"]},
        {question:"Which data type is 42?",correct:["Integer","int"],wrong:["Float","String","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","Decimal","DigitString","NumBlock","WholeNumber"]},
        {question:"Which data type is 3.14?",correct:["Float","float"],wrong:["Integer","String","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","Decimal","DigitString","NumBlock"]},
        {question:"Which data type is True?",correct:["Boolean","bool"],wrong:["String","Integer","Float","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueString","FalseString","WholeNumber","Decimal","DigitString"]},
        {question:"Which data type is used for words and sentences?",correct:["String","str"],wrong:["Integer","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","Decimal","DigitString","NumBlock"]},
        {question:"Which data type is used for numbers with decimal places?",correct:["Float","float"],wrong:["Integer","String","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Char","DataBlock","TrueFalse","WholeNumber","Decimal","DigitString","NumBlock"]},
      
      ],

      "Variables and Values": [
        {question:"What is the variable name in: name = 'Ali'?",correct:["name","The word name"],wrong:["Ali","'Ali'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What is the value in: age = 14?",correct:["14","The number 14"],wrong:["age","=","Python","True","False","Float","String","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit"]},
        {question:"What is the variable name in: score = 10?",correct:["score","The word score"],wrong:["10","'10'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What value is stored in: username = 'sam'?",correct:["'sam'","sam"],wrong:["username","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What is the variable name in: price = 4.99?",correct:["price","The word price"],wrong:["4.99","'4.99'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What value is stored in: logged_in = True?",correct:["True","true"],wrong:["logged_in","=","String","Float","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","False","Value"]},
        {question:"What is the variable name in: colour = 'blue'?",correct:["colour","The word colour"],wrong:["blue","'blue'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What value is stored in: level = 3?",correct:["3","Three"],wrong:["level","=","Python","True","False","Float","String","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit"]},
        {question:"What is the variable name in: city = 'London'?",correct:["city","The word city"],wrong:["London","'London'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What value is stored in: points = 0?",correct:["0","Zero"],wrong:["points","=","Python","True","False","Float","String","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit"]},
        {question:"What is the variable name in: temp = 22?",correct:["temp","The word temp"],wrong:["22","'22'","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
        {question:"What value is stored in: message = 'Hello'?",correct:["'Hello'","Hello"],wrong:["message","=","String","Float","Boolean","List","Tuple","Dictionary","Binary","Byte","Object","Data","Digit","Value"]},
      ],

      "Scratch": [
        {question:"What is a sprite in Scratch?",correct:["A character you can program","An object that performs actions"],wrong:["A background","A sound effect","A variable","A loop","A costume","A project file","A script","A stage","A block","A list","A broadcast","A clone","A motion block","A timer","A message"]},
        {question:"What does the green flag do in Scratch?",correct:["Starts the project","Runs all scripts that use the green flag block"],wrong:["Stops the project","Deletes sprites","Changes backdrop","Saves the project","Creates clones","Adds variables","Plays all sounds","Repeats forever","Broadcasts messages","Turns sprite invisible","Moves sprite","Ends script","Starts timer","Resets score"]},
        {question:"What does 'move 10 steps' do?",correct:["Moves the sprite forward 10 units","Shifts the sprite 10 steps"],wrong:["Rotates sprite","Changes backdrop","Plays sound","Starts loop","Stops script","Moves backward","Deletes sprite","Creates clone","Changes costume","Broadcasts message","Sets x to 10","Sets y to 10","Moves randomly","Starts animation","Saves project"]},
        {question:"What is a backdrop in Scratch?",correct:["The background of the stage","The image behind sprites"],wrong:["A sprite","A sound","A variable","A loop","A script","A clone","A list","A broadcast","A timer","A block","A costume","A project","A message","A function"]},
        {question:"What does 'say Hello for 2 seconds' do?",correct:["Shows a speech bubble","Displays text for 2 seconds"],wrong:["Plays sound","Changes costume","Moves sprite","Starts loop","Stops script","Deletes sprite","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Shows thought bubble","Saves project","Repeats forever"]},
        {question:"What does 'repeat 10' do?",correct:["Repeats the blocks inside 10 times","Loops actions 10 times"],wrong:["Repeats forever","Runs once","Stops script","Creates clone","Changes backdrop","Moves sprite","Plays sound","Starts timer","Deletes sprite","Broadcasts message","Sets variable","Changes costume","Saves project","Randomises movement","Ends script"]},
        {question:"What does 'forever' do?",correct:["Repeats actions endlessly","Loops forever"],wrong:["Runs once","Repeats 10 times","Stops script","Creates clone","Changes backdrop","Moves sprite","Plays sound","Starts timer","Deletes sprite","Broadcasts message","Sets variable","Changes costume","Saves project","Ends script","Randomises movement"]},
        {question:"What does 'wait 1 second' do?",correct:["Pauses the script","Delays actions"],wrong:["Stops project","Deletes sprite","Moves sprite","Starts loop","Plays sound","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Changes costume","Repeats forever","Ends script","Randomises movement"]},
        {question:"What does 'switch costume to costume2' do?",correct:["Changes sprite appearance","Switches to another costume"],wrong:["Moves sprite","Plays sound","Starts loop","Stops script","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Deletes sprite","Repeats forever","Saves project","Randomises movement","Ends script"]},
        {question:"What does 'go to x:0 y:0' do?",correct:["Moves sprite to centre","Places sprite at (0,0)"],wrong:["Deletes sprite","Plays sound","Starts loop","Stops script","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Changes costume","Repeats forever","Moves randomly","Saves project","Ends script"]},
        {question:"What does 'play sound meow' do?",correct:["Plays a sound","Makes sprite meow"],wrong:["Moves sprite","Changes costume","Starts loop","Stops script","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Deletes sprite","Repeats forever","Saves project","Randomises movement","Ends script"]},
        {question:"What does 'hide' do?",correct:["Makes sprite invisible","Hides sprite from stage"],wrong:["Deletes sprite","Stops script","Moves sprite","Starts loop","Plays sound","Creates clone","Changes backdrop","Broadcasts message","Sets variable","Starts timer","Changes costume","Repeats forever","Saves project","Ends script"]}
    ],

      "Maths / Arithmetic": [
        {question:"What does print(4 + 18) output?",correct:["22","The number 22"],wrong:["418","4 + 18","Error","Undefined","40","The number 14","24","The number12","0","A string","Nothing","True","False","Null","Minus 22"]},
        {question:"What does print(3 * 7) output?",correct:["21","The number 21"],wrong:["37","3 * 7","Error","0","The number 10","14","27","30","1","True","False","A string","Null","The number 17","70"]},
        {question:"What does print(10 - 6) output?",correct:["4","The number 4"],wrong:["106","10 - 6","Error","0","The number 6","16","1","The number 10","False","True","A string","Null","Minus 4","40","14"]},
        {question:"What does print(8 / 2) output?",correct:["4.0","4"],wrong:["82","8 / 2","Error","0","The number 2","6","3","1","True","False","A string","Null","Minus 4","The number 40","14"]},
        {question:"What does print(5 + 5) output?",correct:["10","The number 10"],wrong:["55","5 + 5","Error","0","5","The number 15","20","True","False","A string","Null","Minus 10","50","The number 1","25"]},
        {question:"What does print(9 - 3) output?",correct:["6","The number 6"],wrong:["93","9 - 3","Error","0","The number 3","9","12","True","False","A string","Null","Minus 6","60","1","The number30"]},
        {question:"What does print(2 * 9) output?",correct:["18","The number 18"],wrong:["29","2 * 9","Error","0","9","20","16","True","False","A string","Null","Minus 18","81","The number 1","The number 27"]},
        {question:"What does print(12 / 3) output?",correct:["4.0","4"],wrong:["123","12 / 3","Error","0","3","The number 6","9","True","False","A string","Null","Minus 4","40","1","The number 24"]},
        {question:"What does print(7 + 2) output?",correct:["9","The number 9"],wrong:["The number 72","7 + 2","Error","0","The number2","7","10","True","False","A string","Null","Minus 9","90","1","27"]},
        {question:"What does print(20 - 5) output?",correct:["15","The number 15"],wrong:["205","20 - 5","Error","0","The number 5","10","25","True","False","A string","Null","Minus 15","150","1","The number 50"]},
        {question:"What does print(6 * 6) output?",correct:["36","The number 36"],wrong:["66","6 * 6","Error","0","6","The number 12","18","True","False","A string","Null","Minus 36","360","1","The number 60"]},
        {question:"What does print(30 / 5) output?",correct:["6.0","6"],wrong:["305","30 / 5","Error","0","The number 5","10","15","True","False","A string","Null","Minus 6","60","1","The number 25"]}
      ],

      "State the Output (If/Else)": [
        {question:"What is the output of: if 5 > 2: print('Yes') else: print('No')?",correct:["Yes","It prints Yes"],wrong:["No","Error","True","False","5 > 2","2 > 5","Maybe","Undefined","Nothing","Both","Loops","Crashes","YesNo","Prints twice","Stops"]},
        {question:"What is the output of: if 3 == 4: print('Match') else: print('No Match')?",correct:["No Match","It prints No Match"],wrong:["Match","Error","True","False","3 == 4","Undefined","Nothing","Both","Loops","Stops","Prints 3","Prints 4","Mismatch","Null","Crash"]},
        {question:"What is the output of: if 10 < 1: print('Small') else: print('Big')?",correct:["Big","It prints Big"],wrong:["Small","Error","True","False","10 < 1","Undefined","Nothing","Both","Loops","Stops","Prints 10","Prints 1","Null","Crash","Tiny"]},
        {question:"What is printed: if 1 == 1: print('Correct') else: print('Wrong')?",correct:["Correct","It prints Correct"],wrong:["Wrong","Error","True","False","1 == 1","Undefined","Nothing","Both","Loops","Stops","Null","Crash","1","0"]},
        {question:"What is printed: if 2 > 9: print('High') else: print('Low')?",correct:["Low","It prints Low"],wrong:["High","Error","True","False","2 > 9","Undefined","Nothing","Both","Loops","Stops","Null","Crash","2","9"]},
        {question:"What is printed: if 7 == 7: print('Same') else: print('Different')?",correct:["Same","It prints Same"],wrong:["Different","Error","True","False","7 == 7","Undefined","Nothing","Both","Loops","Stops","Null","Crash","7","77"]},
        {question:"What is printed: if 4 < 2: print('Yes') else: print('No')?",correct:["No","It prints No"],wrong:["Yes","Error","True","False","4 < 2","Undefined","Nothing","Both","Loops","Stops","Null","Crash","4","2"]},
        {question:"What is printed: if 8 > 3: print('Bigger') else: print('Smaller')?",correct:["Bigger","It prints Bigger"],wrong:["Smaller","Error","True","False","8 > 3","Undefined","Nothing","Both","Loops","Stops","Null","Crash","8","3"]},
        {question:"What is printed: if 0 == 1: print('Equal') else: print('Not Equal')?",correct:["Not Equal","It prints Not Equal"],wrong:["Equal","Error","True","False","0 == 1","Undefined","Nothing","Both","Loops","Stops","Null","Crash","0","1"]},
        {question:"What is printed: if 9 < 20: print('OK') else: print('NO')?",correct:["OK","It prints OK"],wrong:["NO","Error","True","False","9 < 20","Undefined","Nothing","Both","Loops","Stops","Null","Crash","9","20"]},
        {question:"What is printed: if 2 == 3: print('Yes') else: print('No')?",correct:["No","It prints No"],wrong:["Yes","Error","True","False","2 == 3","Undefined","Nothing","Both","Loops","Stops","Null","Crash","2","3"]},
        {question:"What is printed: if 11 > 1: print('Go') else: print('Stop')?",correct:["Go","It prints Go"],wrong:["Stop","Error","True","False","11 > 1","Undefined","Nothing","Both","Loops","Stops","Null","Crash","11","1"]}
    ],

    "Sequence, Selection, Iteration": [

        {question:"What is sequence in programming?",correct:["Steps executed in order","Instructions that run one after another"],wrong:["A loop","A condition","A variable","A sprite","A sound","Random actions","A function","A bug","A list","A broadcast","A clone","A timer","A repeat block","A backdrop","A message"]},
        {question:"What is selection in programming?",correct:["Choosing between options","Using conditions to decide"],wrong:["Repeating actions","Running steps in order","A variable","A sprite","A sound","A function","A bug","A list","A broadcast","A clone","A timer","A backdrop","A message","A print statement"]},
        {question:"What is iteration in programming?",correct:["Repeating instructions","A loop that repeats actions"],wrong:["A single step","A condition","A variable","A sprite","A sound","A function","A bug","A list","A broadcast","A clone","A timer","A backdrop","A message","A print statement","A calculation"]},
        {question:"Which is an example of sequence?",correct:["print('Hello') then print('World')","Two steps in order"],wrong:["if statement","while loop","for loop","variable assignment","sprite movement","sound playing","random number","broadcast","clone","timer","backdrop change","message","function","list"]},
        {question:"Which is an example of selection?",correct:["if score > 10: print('Win')","Using an if statement"],wrong:["print statements","loops","lists","variables","functions","sprites","sounds","broadcasts","clones","timers","backdrops","messages","random numbers","costumes","movement"]},
        {question:"Which is an example of iteration?",correct:["repeat 10 times","A loop that repeats"],wrong:["if statement","single print","variable","list","function","sprite","sound","broadcast","clone","timer","backdrop","message","random number","costume","movement"]},
        {question:"What does a condition check?",correct:["Whether something is true","A true or false test"],wrong:["Repeats actions","Runs steps in order","Creates variables","Moves sprites","Plays sounds","Starts project","Ends script","Creates clones","Changes backdrop","Sets timer","Saves project","Randomises movement","Changes costume","Deletes sprite"]},
        {question:"What does a loop do?",correct:["Repeats actions","Runs code multiple times"],wrong:["Checks conditions","Runs once","Creates variables","Moves sprites","Plays sounds","Starts project","Ends script","Creates clones","Changes backdrop","Sets timer","Saves project","Randomises movement","Changes costume","Deletes sprite"]},
        {question:"What does an if statement do?",correct:["Chooses what to run","Makes decisions"],wrong:["Repeats actions","Runs steps in order","Creates variables","Moves sprites","Plays sounds","Starts project","Ends script","Creates clones","Changes backdrop","Sets timer","Saves project","Randomises movement","Changes costume","Deletes sprite"]},
        {question:"What is the purpose of sequence?",correct:["Ensure steps run in order","Control program flow"],wrong:["Repeat actions","Make decisions","Store data","Move sprites","Play sounds","Start project","End script","Create clones","Change backdrop","Set timer","Save project","Randomise movement","Change costume","Delete sprite"]},
        {question:"What is the purpose of selection?",correct:["Choose between paths","Run code only if true"],wrong:["Repeat actions","Run steps in order","Store data","Move sprites","Play sounds","Start project","End script","Create clones","Change backdrop","Set timer","Save project","Randomise movement","Change costume","Delete sprite"]},
        {question:"What is the purpose of iteration?",correct:["Repeat code efficiently","Loop actions"],wrong:["Make decisions","Run steps in order","Store data","Move sprites","Play sounds","Start project","End script","Create clones","Change backdrop","Set timer","Save project","Randomise movement","Change costume","Delete sprite"]}
    ]

    },

  "Laws and Regulations": {

      "Data Protection Act": [
        {question:"What does GDPR stand for?",correct:["General Data Protection Regulation","General data protection regulation"],wrong:["Global Data Privacy Rule","General Data Privacy Regulation","Global Data Protection Regulation","General Data Protection Rule","Global Data Privacy Regulation","General Data Privacy Rule","Global Data Protection Rule","General Data Privacy Act","Global Data Privacy Act","General Data Protection Act","Global Data Protection Law","General Data Privacy Law","Global Data Protection Policy","General Data Privacy Policy"]},
        {question:"What is the main purpose of GDPR?",correct:["Protect personal data and privacy","Regulate data protection and privacy"],wrong:["Allow free data sharing","Promote data collection","Regulate internet usage","Control online content","Manage social media use","Enforce copyright laws","Regulate advertising online","Control software development","Manage hardware manufacturing","Enforce cybersecurity measures","Regulate e-commerce activities","Control online communication","Manage digital marketing practices"]},
        {question:"What does the Data Protection Act protect?",correct:["Personal data","Private information"],wrong:["Computer speed","WiFi strength","Screen brightness","Keyboard layout","Mouse settings","Printer ink","Speaker volume","Battery life","Fan speed","GPU heat","Cable types","Monitor size","Game scores","Music files","Video quality"]},
        {question:"What is personal data?",correct:["Information about a person","Details like name or address"],wrong:["WiFi password","PC speed","Screen size","Keyboard colour","Mouse DPI","Printer ink","Speaker volume","Battery level","Fan speed","GPU heat","Cable types","Monitor size","Game scores","Music files","Video quality"]},
        {question:"Why must companies keep data secure?",correct:["Protect people","Prevent misuse"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be accurate?",correct:["Avoid mistakes","Keep records correct"],wrong:["Make PC faster","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be kept only as long as needed?",correct:["Reduce risk","Protect privacy"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be collected fairly?",correct:["Be honest","Follow rules"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be used only for its purpose?",correct:["Follow the law","Protect privacy"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be kept safe from hackers?",correct:["Protect people","Prevent crime"],wrong:["Speed up PC","Improve graphics","Stop spills","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must people be allowed to see their own data?",correct:["Check accuracy","Know what is stored"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be kept up to date?",correct:["Avoid mistakes","Stay correct"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be stored securely?",correct:["Prevent leaks","Protect privacy"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must companies follow data rules?",correct:["Follow the law","Protect people"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data not be shared without permission?",correct:["Protect privacy","Follow rules"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must data be stored safely online?",correct:["Prevent hacking","Protect users"],wrong:["Speed up PC","Improve graphics","Stop spills","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must companies delete data when no longer needed?",correct:["Protect privacy","Reduce risk"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]}
      ],

      "Computer Misuse Act": [

        {question:"What does the Computer Misuse Act protect against?",correct:["Hacking","Unauthorised access"],wrong:["Eye strain","Back pain","Spills","Slow WiFi","Broken screens","Printing errors","Low battery","Full storage","Loud fans","Old software","Weak speakers","Loose cables","Dust","Overheating","Bad posture"]},
        {question:"What is unauthorised access?",correct:["Using a system without permission","Logging in without rights"],wrong:["Typing slowly","Printing pages","Saving files","Playing music","Browsing safely","Charging devices","Adjusting chairs","Cleaning screens","Using headphones","Writing emails","Editing photos","Scanning images","Playing games","Installing updates"]},
        {question:"What is malware?",correct:["Harmful software","Software that damages systems"],wrong:["Healthy apps","Safe programs","Strong passwords","Clean code","Fast WiFi","Good graphics","Bright screens","New keyboards","Charged batteries","Printed pages","Scanned files","Recorded audio","Edited photos","Saved documents","Installed updates"]},
        {question:"Why is guessing someone’s password illegal?",correct:["Breaks the law","Unauthorised access"],wrong:["Makes PC slow","Uses battery","Prints badly","Hurts eyes","Breaks keyboard","Uses storage","Plays music","Edits code","Scans files","Records sound","Designs networks","Writes emails","Runs updates","Manages RAM","Changes brightness"]},
        {question:"What is the purpose of the Computer Misuse Act?",correct:["Stop cybercrime","Protect systems"],wrong:["Fix posture","Improve WiFi","Stop spills","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"What is hacking?",correct:["Breaking into systems","Accessing without permission"],wrong:["Typing fast","Printing pages","Saving files","Playing music","Browsing safely","Charging devices","Adjusting chairs","Cleaning screens","Using headphones","Writing emails","Editing photos","Scanning images","Playing games","Installing updates"]},
        {question:"Why is spreading malware illegal?",correct:["It harms systems","Breaks the law"],wrong:["Slows typing","Uses ink","Makes screens dim","Uses battery","Makes fans loud","Uses storage","Plays music","Edits code","Scans files","Records sound","Designs networks","Writes emails","Runs updates","Manages RAM","Changes brightness"]},
        {question:"What is phishing?",correct:["Tricking people for information","Fake messages"],wrong:["Cleaning screens","Fixing PCs","Printing pages","Saving files","Playing music","Browsing safely","Charging devices","Adjusting chairs","Editing photos","Scanning images","Playing games","Installing updates","Designing networks","Writing emails","Managing RAM"]},
        {question:"Why is deleting someone else’s files illegal?",correct:["Unauthorised modification","Breaks the law"],wrong:["Slows PC","Uses battery","Prints badly","Hurts eyes","Breaks keyboard","Uses storage","Plays music","Edits code","Scans files","Records sound","Designs networks","Writes emails","Runs updates","Manages RAM","Changes brightness"]},
        {question:"What is the penalty for hacking?",correct:["Fines","Prison"],wrong:["Free WiFi","Free software","Better graphics","Faster PC","New keyboard","New mouse","Free printer","Free apps","More storage","Better speakers","New monitor","Free games","Free updates","Free cables","Free headphones"]},
        {question:"Why must passwords be kept private?",correct:["Prevent hacking","Stay secure"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"What is a strong password?",correct:["Hard to guess","Secure"],wrong:["Your name","1234","password","abc","qwerty","birthday","pet name","school name","football team","favourite food","simple words","short words","easy numbers","single letter","single digit"]},
        {question:"Why is installing illegal software wrong?",correct:["Breaks the law","Unsafe"],wrong:["Slows PC","Uses battery","Prints badly","Hurts eyes","Breaks keyboard","Uses storage","Plays music","Edits code","Scans files","Records sound","Designs networks","Writes emails","Runs updates","Manages RAM","Changes brightness"]},
        {question:"What is a cyber attack?",correct:["Attempt to damage systems","Online attack"],wrong:["Typing fast","Printing pages","Saving files","Playing music","Browsing safely","Charging devices","Adjusting chairs","Cleaning screens","Using headphones","Writing emails","Editing photos","Scanning images","Playing games","Installing updates"]},
        {question:"Why must users log out when finished?",correct:["Prevent misuse","Stay secure"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]}
      ],

      "Health and Safety Act": [
        
        {question:"What is the main purpose of the Health and Safety Act?",correct:["Keep people safe","Prevent accidents"],wrong:["Hack computers","Steal data","Delete files","Make websites","Print documents","Play games","Install apps","Browse the web","Design hardware","Write emails","Record audio","Scan images","Play music","Edit videos","Run updates"]},
        {question:"Why must drinks be kept away from computers?",correct:["Avoid spills","Prevent damage"],wrong:["Make PC faster","Improve graphics","Stop viruses","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should cables be tucked away?",correct:["Prevent trips","Keep area safe"],wrong:["Speed up WiFi","Make screens brighter","Stop hacking","Store data","Print faster","Play games","Install apps","Record sound","Scan files","Edit code","Design networks","Write emails","Play music","Run updates","Manage RAM"]},
        {question:"Why should chairs be adjusted correctly?",correct:["Prevent injury","Improve posture"],wrong:["Speed up CPU","Make screen brighter","Stop hacking","Store data","Print pages","Play games","Install apps","Browse the web","Record sound","Scan files","Edit code","Write emails","Play music","Run updates","Manage RAM"]},
        {question:"Why should students take breaks when using computers?",correct:["Avoid eye strain","Prevent tiredness"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must computer rooms be kept tidy?",correct:["Prevent accidents","Keep safe"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should monitors be at eye level?",correct:["Reduce neck strain","Improve comfort"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must heavy equipment be lifted correctly?",correct:["Avoid injury","Protect back"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should wires not be damaged?",correct:["Prevent shocks","Stay safe"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must ventilation be clear around computers?",correct:["Prevent overheating","Keep safe"],wrong:["Speed up WiFi","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should students report broken equipment?",correct:["Prevent injury","Fix problems"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must chairs have back support?",correct:["Prevent back pain","Improve posture"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should screens not be too bright?",correct:["Prevent eye strain","Reduce headaches"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why must computer rooms have good lighting?",correct:["Reduce eye strain","Improve visibility"],wrong:["Speed up PC","Improve graphics","Stop hacking","Print better","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]},
        {question:"Why should students sit correctly at computers?",correct:["Prevent injury","Stay comfortable"],wrong:["Speed up PC","Improve WiFi","Stop viruses","Print faster","Store files","Play videos","Install apps","Browse websites","Record audio","Scan images","Play games","Edit code","Write emails","Design hardware","Run updates"]}
      ]



  },

},

"KS4": {
  "Cambridge_Nationals_IT_Level_2": {
    "R050: IT in the Digital World": {
      "Design Tools": {
        "Purpose of design tools": [
          {question:"What is the purpose of a mood board?",correct:["Show ideas","Give visual style"],wrong:["Write code","Store files","Print documents","Play music","Edit videos","Browse websites","Make spreadsheets","Send emails","Run the OS","Install software","Manage hardware","Record audio","Draw diagrams","Scan documents","Play games","Design databases"]},
          {question:"Why are design tools used before creating a product?",correct:["Plan ideas","Show layout"],wrong:["Fix errors","Print pages","Store data","Play videos","Install apps","Manage RAM","Control hardware","Run updates","Browse the web","Make backups","Scan files","Play music","Send messages","Record sound","Run games","Edit photos"]},
          {question:"What is the purpose of a storyboard?",correct:["Show sequence","Plan scenes"],wrong:["Store files","Print documents","Play audio","Edit code","Manage networks","Install drivers","Run the OS","Make spreadsheets","Browse websites","Record video","Scan images","Play games","Design hardware","Write emails","Edit photos","Create backups"]},
          {question:"What is the purpose of a wireframe?",correct:["Show layout","Plan structure"],wrong:["Play music","Store data","Print pages","Run apps","Edit videos","Browse the web","Install software","Manage RAM","Record audio","Scan documents","Play games","Design hardware","Write emails","Make spreadsheets","Edit photos","Run updates"]},
          {question:"What is the purpose of a visualisation diagram?",correct:["Show design","Plan appearance"],wrong:["Store files","Print documents","Play videos","Install apps","Manage hardware","Run the OS","Browse websites","Record sound","Scan images","Play games","Edit code","Make spreadsheets","Write emails","Design networks","Edit photos","Create backups"]},
          {question:"Why do designers use design tools?",correct:["Plan ideas","Communicate designs"],wrong:["Fix hardware","Install software","Play music","Print pages","Store data","Run updates","Browse the web","Record audio","Scan documents","Play games","Edit code","Make spreadsheets","Write emails","Edit photos","Design networks","Manage RAM"]},
          {question:"What do design tools help identify?",correct:["Client needs","Key features"],wrong:["CPU speed","RAM size","Disk space","Network type","Printer ink","Monitor size","Mouse settings","Keyboard layout","Speaker volume","Battery level","Cable types","Power usage","Fan speed","GPU temperature","Screen brightness","WiFi password"]},
          {question:"What is the purpose of showing layout in design tools?",correct:["Plan placement","Organise content"],wrong:["Play videos","Store files","Print pages","Run apps","Install software","Manage hardware","Browse websites","Record audio","Scan images","Play games","Edit code","Make spreadsheets","Write emails","Edit photos","Design networks","Run updates"]},
          {question:"Why do designers use annotations on design tools?",correct:["Explain ideas","Add details"],wrong:["Play music","Store data","Print pages","Run apps","Edit videos","Browse the web","Install software","Manage RAM","Record audio","Scan documents","Play games","Design hardware","Write emails","Make spreadsheets","Edit photos","Run updates"]},
          {question:"What is the purpose of design tools in R050?",correct:["Plan products","Show ideas"],wrong:["Fix errors","Install apps","Play music","Print pages","Store files","Run updates","Browse websites","Record sound","Scan images","Play games","Edit code","Make spreadsheets","Write emails","Edit photos","Design networks","Manage hardware"]}
        ],

        "Types of design tools": [
          {question:"What design tool is used to show the appearance of a finished product?",correct:["Visualisation diagram","Viz Diagram"],wrong:["MOOD BOARD","Flowchart","Mind map","High fidelity wireframe","LOW FIDELITY WIREFRAME","Powerpoint","Microsoft Word","Microsoft Excel","Mood bord","Flow chat","Mind mape","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to sketch basic page layouts before development?",correct:["Low fidelity wireframe","LOW FIDELITY WIREFRAME"],wrong:["Mood board","FLOWCHART","Mind map","High fidelity wireframe","Visualisation diagram","POWERPOINT","MICROSOFT WORD","MICROSOFT EXCEL","MOOD BOARD","Flow chat","Mind mape","Visualisation digram","High fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to show detailed screen designs with colours and fonts?",correct:["High fidelity wireframe","HIGH FIDELITY WIREFRAME"],wrong:["Mood board","Flowchart","MIND MAP","LOW FIDELITY WIREFRAME","Visualisation diagram","High Fodility wirefram","Microsoft Powerpoint","Microsft Word","Mood bord","Flow chat","Mind mape","Visualisation digram","Low fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to organise ideas around a central topic?",correct:["Mind map","MIND MAP"],wrong:["MOODBOARD","Flowchart","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Mind mape","Muindmap","Minde map","Mood bord","MICROSOFT EXCEL","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Microsoft powerpoint","Microsoft word"]},
          {question:"What design tool is used to show the steps in a process?",correct:["Flowchart","FLOWCHART"],wrong:["Mood board","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Flechart","Fluwchartt","PIE chart","Mood bord","Mind mape","Visualisation digram","High fidelity wirefram","Microsoft Word","Moodboard","Minde map"]},
          {question:"What design tool is used to collect colours, images and style ideas?",correct:["Mood board","MOOD BOARD"],wrong:["Flowchart","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Microsoft Word","MOODBEARD","MOOD BOAAD","Flow chat","Mind mape","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Minde map"]},
          {question:"What design tool is used to show how users move between screens?",correct:["Flowchart","FLOWCHART"],wrong:["Mood board","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Flechart","Flowchartt","PIE chart","Mood bord","Mind mape","Visualisation digram","MICROSOFT POWERPOINT","Microsoft Word","Moodboard","Minde map"]},
          {question:"What design tool is used to generate and connect ideas during planning?",correct:["Mind map","MIND MAP"],wrong:["MOODBOARD","Flowchart","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Mind mape","Mindmap","Minde map","Mood bord","MICROSOFT EXCEL","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Microsoft powerpoint","Microsoft word"]},
          {question:"What design tool is used to provide a realistic preview of a product?",correct:["Visualisation diagram","VISUALISATION DIAGRAM"],wrong:["MOOD BOARD","Flowchart","Mind map","High fidelity wireframe","LOW FIDELITY WIREFRAME","Powerpoint","Microsoft Word","Microsoft Excel","Mood bord","Flow chat","Mind mape","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to show the structure of a website using simple sketches?",correct:["Low fidelity wireframe","LOW FIDELITY WIREFRAME"],wrong:["Mood board","FLOWCHART","Mind map","High fidelity wireframe","Visualisation diagram","POWERPOINT","MICROSOFT WORD","MICROSOFT EXCEL","MOOD BOARD","Flow chat","Mind mape","Visualisation digram","Luw fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to present branding and theme ideas?",correct:["Mood board","MOOD BOARD"],wrong:["Flowchart","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Microsoft Word","MOODBEARD","MOOD BOAAD","Flow chat","Mind mape","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Minde map"]},
          {question:"What design tool is used to show exactly where interface elements will be placed?",correct:["High fidelity wireframe","HIGH FIDELITY WIREFRAME"],wrong:["Mood board","Flowchart","Mind map","Low fidelity wireframe","Visualisation diagram","High fidelity wirefram","Hugh-fidelity wireframe","Microsoft Word","Mood bord","Flow chat","Microsoft Powerpoint","VIZ DIAGRAM","Low fidelity wirefram","Flowchartt","MOODBOARD"]},
          {question:"What design tool is used to identify relationships between ideas?",correct:["Mind map","MIND MAP"],wrong:["MOODBOARD","Flowchart","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Mind mape","Mindmap","Minde map","Mood bord","MICROSOFT EXCEL","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Microsoft powerpoint","Microsoft word"]},
          {question:"What design tool is used to show decision paths using arrows and symbols?",correct:["Flowchart","FLOWCHART"],wrong:["Mood board","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","FLECHART","Flowechartt","PIE chart","Mood bord","Mind mape","Visualisation digram","High fidelity wirefram","Microsoft Word","Moodboard","Minde map"]},
          {question:"What design tool is used to show the final look of a user interface?",correct:["Visualisation diagram","Viz Diagram"],wrong:["MOOD BOARD","Flowchart","Mind map","High fidelity wireframe","LOW FIDELITY WIREFRAME","Powerpoint","Microsoft Word","Microsoft Excel","Mood bord","Flow chat","Mind mape","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to create a rough draft of screen layouts?",correct:["Low fidelity wireframe","LOW FIDELITY WIREFRAME"],wrong:["Mood board","FLOWCHART","Mind map","High fidelity wireframe","Visualisation diagram","POWERPOINT","MICROSOFT WORD","MICROSOFT EXCEL","MOOD BOARD","Flow chat","Mind mape","Visualisation digram","Luw fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to display detailed interactive screen designs?",correct:["High fidelity wireframe","HIGH FIDELITY WIREFRAME"],wrong:["Mood board","Flowchart","MIND MAP","LOW FIDELITY WIREFRAME","Visualisation diagram","High Fodility wirefram","Microsoft Powerpoint","Microsft Word","Mood bord","Flow chat","Mind mape","Visualisation digram","Low fidelity wirefram","Flowchartt","Moodboard"]},
          {question:"What design tool is used to gather inspiration before creating a product?",correct:["Mood board","MOOD BOARD"],wrong:["Flowchart","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Microsoft Word","MOODBEARD","MOOD BOAAD","Flow chat","Mind mape","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Flowchartt","Minde map"]},
          {question:"What design tool is used to map out navigation through an application?",correct:["Flowchart","FLOWCHART"],wrong:["Mood board","Mind map","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Flechart","Flowchartt","PIE chart","Mood bord","Mind mape","Visualisation digram","MICROSOFT POWERPOINT","Microsoft Word","Moodboard","Minde map"]},
          {question:"What design tool is used to brainstorm features for a new product?",correct:["Mind map","MIND MAP"],wrong:["MOODBOARD","Flowchart","High fidelity wireframe","Low fidelity wireframe","Visualisation diagram","Mind mape","Mindmap","Minde map","Mood bord","MICROSOFT EXCEL","Visualisation digram","High fidelity wirefram","Low fidelity wirefram","Microsoft powerpoint","Microsoft word"]},
       ]
      }
    }
  }
},


"KS5": {}

}
